### ISSUE TITLE
Unable to complete account linking

### ISSUE THREAD

**Issue by realroywalker** [infinityofspace/jellyfin_alexa_skill#46]
### Describe the bug

[comment]: <> (A clear and concise description of what the bug is.)

I am trying to setup the skill but cannot complete the account linking process - I see the Jellyfin credentials page (not the usual Jellyfin one, so I guess this is served by the skill) and after submitting the credentials I get 

'Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.'

Watching the log for the jellyfin_alexa_skill docker container gives no clues at to what the issue is (the output just stays on "Booting worker with pid: 28" as the last line).

### To Reproduce

[comment]: <> (Steps to reproduce the behavior.)

I believe i've set up everything as per the instructions, but was not sure how I should answer some of the questions for 'ask-cli config'.
I have a caddy reverse proxy already configured, so have forwarded jellyfin.mydomain.com (443) to the jellyfin server (8096) and jellyfinalexa.mydomain.com (443) to the jellyfin_alexa_skill container (1456), the caddy proxy is configured with LetsEncrypt certificates.

My skill.conf contains;

[general]
skill_id = amzn1.ask.skill.xxxxxxxxxxxxxxxx
web_app_port = 1456
jellyfin_endpoint = https://jellyfin.mydomain.com
skill_endpoint = https://jellyfinalexa.mydomain.com
skill_endpoint_ssl_cert_type = trusted
force_reset_skill = false

[ngrok]
auth_token = 
region = 
jellyfin_addr = 

[smapi]
client_id = amzn1.application-oa2-client.xxxxxxxxxxxxxxxxxxxxxxxxx
client_secret = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
refresh_token = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

[data]
alexa_account_linking_client_id = xxxxxxxxxxxx
flask_secret = xxxxxxxxxxxxxxxxxxxx

### Expected behavior

[comment]: <> (A clear and concise description of what you expected to happen.)

To be able to link the alexa skill with Jellyfin

### Versions

[comment]: <> (Please complete the following version information.)

 - Are you using the Docker image or the Python package?: [write docker or pip as answer] Docker
 - jellyfin_alexa_skill: [you can use `pip show jellyfin_alexa_skill` to get the version] 0.3.1

### Additional context

[comment]: <> (Add any other context about the problem here. E.g. Logs and error messages.)

(Write your answer here.)

**Comment by infinityofspace** [comment]
Thanks for your bug report.

Currently logs from Flask are not displayed, because a WSGI server is used and the logs are not passed through correctly, except exceptions. Therefore it does not help to use the --verbose flag when we want to se very verbose logs.  I already added a feature issue to make debugging easier #49.

Since the skill starts correctly, otherwise you would get corresponding error messages when starting and setting it up, the problem is most likely that it cannot reach your Jellyfin instance or the issue pop up when the credentials token should be saved in the db. 

Could you please check if your Jellyfin instance is accessible from the Docker container via the given url.
You can use the following commands to do this (while the skill is running):
```commandline
docker exec -it <name-of-the-container> sh
curl https://jellyfin.mydomain.com
```

To rule out a problem with the DB, please try deleting the Docker volume or mounted folder and running the setup again.

If the error occurs again, it would be helpful for troubleshooting if you could post the url from the error page. Make sure to replace the corresponding tokens/ID with placeholders like `<token1>`, `<id1>` or `<token2>` etc. Because it would also be possible that the forwarding to the Alexa page and thus the linking of the Skill and the Alexa account causes problems.

**Comment by realroywalker** [comment]
Thanks for the quick response, I found the issue with the help of your tip regarding it being comms between the container and my jellyfin server. I went through all the Jellyfin options again and noticed a tick box to enable remote access under the networking config (in addition to the one I'd already ticked for the user!) - now the skill links ok, I can't test it yet since my library is busy scanning which seems to make jellyfin pretty much unusable..

I noticed that in the Jellyfin options there is a whitelist option for remote access - do you know if there is a specific IP / range that Amazon will be accessing my server on? 
Ideally I'd like to whitelist the remote access just to the required Amazon range or address for a little extra security, since I don't need general remote access from anywhere else.

**Comment by infinityofspace** [comment]
> I noticed that in the Jellyfin options there is a whitelist option for remote access - do you know if there is a specific IP / range that Amazon will be accessing my server on?
Ideally I'd like to whitelist the remote access just to the required Amazon range or address for a little extra security, since I don't need general remote access from anywhere else.

In the Alexa docs, unfortunately, I did not find any IP range or similar. My instance receives IP range requests from AWS, but sometimes they change. Therefore, you would have to enter all AWS data centers in an IP Allow list, which of course does not make much sense.

There is currently a feature idea to forward connections from Cloud Alexa to the jellyfin server via the Alexa skill to solve #4, so the jellyfin skill would control the access to the jellyfin server. Because currently Cloud Alexa receives a token to the jellyfin instance that allows it to stream the media, but this token has more rights than necessary. This solution idea would match your idea, as you could then put the container from the jellyfin alexa skill on the allow list and block other external access.
Otherwise, this feature idea with the forwarding is worth a separate ticket #50. So I this feature goes to the project plan.

**Comment by realroywalker** [comment]
Thanks for the information, good to hear that something is in the pipeline to restrict access to the bare minimum.
I have tested the skill now my library has scanned and basic functions seem to work (with some glitches).

I have noted that when completing the account linking process Chrome reports that I should not enter my password into the docker services authentication page for the Jellyfin account details - it comes up saying it is a 'Deceptive Site' (not sure why, as my certificate etc. is all OK).
Chrome now also shows this under my stored passwords;
![Screenshot 2022-05-18 145553](https://user-images.githubusercontent.com/486860/169059722-4bac6ed6-08a0-4023-b0eb-368816cdd892.png)

A few additional things:
- Is there is diagram anywhere that shows how everything (Jellyfin Server, Docker and AWS/Amazon) link together to make this work ? I'm currently not 100% clear how it functions so would be nice to understand by seeing something visually.
- Do you want bugs raised for issues encountered while using the skill ? (Given you do already note that it's a work in progress 😄 )

Thanks for your efforts!

**Comment by realroywalker** [comment]
Thanks for the comments, I've now reconfigured my setup to use a cloudfront tunnel rather than my previous nginx reverse proxy - I've removed the saved credentials and relinked the skill without warning from Chrome this time.. so it's possible it could be something with my old setup that triggered this message!

Consider this closed - great job on the skill so far 👍
