### ISSUE TITLE
server fails "Database password is not set"

### ISSUE THREAD

**Issue by Yahoo-Mike** [infinityofspace/jellyfin_alexa_skill#62]
### Describe the bug

I fetched latest code on main branch.  When I rebuild and run the docker container, I get a fatal error: "Database password is not set" from config.py.

I suspect it has to do with the migration to postgres.  Maybe I'm missing a step?

I tried to update my local docker_compose.yml (called _alexa_skill.yml_) with the changes for postgres, but have multiple issues.
First, docker-compose complains that version 3.8 doesn't exist:
```
ERROR: Version in "./alexa_skill.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```
So I changed the version to 3.3.  Docker-compose then complains about the volumes definition of _skills_db_data_:  
```
ERROR: The Compose file './alexa_skill.yml' is invalid because:
volumes.skill_db_data value Additional properties are not allowed ('name' was unexpected)
```

Any ideas what I'm doing wrong?

### Versions
I'm building a docker container from the latest code on main branch.

OS: Ubuntu Server 20.04 LTS
docker: 20.10.17
docker-compose: 1.25.0
python: 3.8.10

**Comment by infinityofspace** [comment]
Thanks for the bug report.

> First, docker-compose complains that version 3.8 doesn't exist

> So I changed the version to 3.3. Docker-compose then complains about the volumes definition of skills_db_data

> docker-compose: 1.25.0

Your docker compose version is too old (3 years). You should update to the latest `2.6.0` or the old python based `1.29.2` version. The newer versions introduced the support for compose file version `3.8`.

In general, you should only use the tagged release versions of the code (e.g. [0.3.1](https://github.com/infinityofspace/jellyfin_alexa_skill/releases/tag/0.3.1)) if you want to use a stable version. Because builds from main are not stable and can contain undocumented breaking changes.

**Comment by Yahoo-Mike** [comment]
I upgraded docker-compose to v2.6.0, as you suggested.  And I fetched the tagged source for 0.3.1.  All working again.

Thanks.
